### ISSUE TITLE
Does not include the branch or tag information

### ISSUE THREAD

**Issue by jnatherley** [zhangyuheng/last-commit-log#1]
Testing the latest release it doesn't return any information on the tags or current branch :)

**Comment by zhangyuheng** [comment]
Sorry i removed the branch and tag features since the server (ci service) may checkout a **commit** instead of a **branch** so the branch name is lost.

```bash
» git branch
* (HEAD detached at 0c996d3)
```
It only include the information which is consistent in different ci services

**Comment by zhangyuheng** [comment]
@jnatherley tag and current branch name added
